# Generated by Django 5.0.3 on 2024-03-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.TextField()),
                ('endereco', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
