# Generated by Django 5.0.3 on 2024-03-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodelo', '0003_produto_remove_cliente_idade_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodelo.cliente')),
                ('produtos', models.ManyToManyField(to='appmodelo.produto')),
            ],
        ),
    ]
